services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop-qa-env
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    environment:
      # Configuración óptima para ambientes de prueba
      NODE_ENV: test